.TH EOS 1 "March 2026" "eos-breathing-room 1.0.0" "User Commands"
.SH NAME
eos \- run Eos Breathing Room local web server
.SH SYNOPSIS
.B eos
.SH DESCRIPTION
.B eos
starts the Eos Breathing Room FastAPI application on
.B 127.0.0.1:8000
using uvicorn.
.PP
Open the app in a browser at:
.B http://127.0.0.1:8000
.SH FILES
.TP
.I /usr/share/eos-breathing-room
Application templates and static assets.
.SH AUTHOR
istax <support@eos-app.net>
